/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ParrotExample {
    }
    interface PartyParrot {
        "storageId"?: string;
    }
}
declare global {
    interface HTMLParrotExampleElement extends Components.ParrotExample, HTMLStencilElement {
    }
    var HTMLParrotExampleElement: {
        prototype: HTMLParrotExampleElement;
        new (): HTMLParrotExampleElement;
    };
    interface HTMLPartyParrotElement extends Components.PartyParrot, HTMLStencilElement {
    }
    var HTMLPartyParrotElement: {
        prototype: HTMLPartyParrotElement;
        new (): HTMLPartyParrotElement;
    };
    interface HTMLElementTagNameMap {
        "parrot-example": HTMLParrotExampleElement;
        "party-parrot": HTMLPartyParrotElement;
    }
}
declare namespace LocalJSX {
    interface ParrotExample {
    }
    interface PartyParrot {
        "storageId"?: string;
    }
    interface IntrinsicElements {
        "parrot-example": ParrotExample;
        "party-parrot": PartyParrot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "parrot-example": LocalJSX.ParrotExample & JSXBase.HTMLAttributes<HTMLParrotExampleElement>;
            "party-parrot": LocalJSX.PartyParrot & JSXBase.HTMLAttributes<HTMLPartyParrotElement>;
        }
    }
}
